services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-FinanceTracker}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "6000:5432"

volumes:
  postgres_data:
