server {
    listen 80;

    include /etc/nginx/locations.conf;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    include /etc/nginx/locations.conf;
}
