name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-checks.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  docker:
    needs: ci
    uses: ./.github/workflows/docker-images.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      push: false
    secrets: inherit
